APPS-8749-update-dependencies
cloudinary/cloudinary-video-player pull request #236
Opened 2021-03-18 09:47 UTC by tsi

https://cloudinary.atlassian.net/browse/APPS-8749

2021-04-13 09:58 UTC, maoznir requested changes

2021-04-13 09:58 UTC, maoznir commented on package.json
>      "dashjs": "^3.2.1",
lets update to ^3.2.2

2021-04-22 09:22 UTC, tsi commented on package.json
>      "dashjs": "^3.2.1",
done

2021-04-23 08:29 UTC, maoznir approved these changes

2021-04-23 08:30 UTC, merged